apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pod
  labels:
    app: my-single-pod-chart
spec:
  replicas: {{ .Values.replicaCount }}
  containers:
    - name: {{ .Release.Name }}-container
      image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      ports:
        - containerPort: 80
